# Generated by Django 5.2.16 on 2026-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvextract',
            name='contact',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cvextract',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvextract',
            name='total_experience_years',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
