# Generated by Django 5.2.15 on 2026-07-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('experience', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume / CV')),
                ('cover_letter', models.TextField(verbose_name='Why join us?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
