# Generated by Django 6.0.7 on 2026-07-16 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('slug', models.SlugField(help_text='Used in URL: /slug/...', max_length=100, unique=True, verbose_name='Slug')),
                ('brand_color', models.CharField(default='#f59e0b', help_text='Hex color for branding', max_length=7, verbose_name='Brand Color')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('experience', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume / CV')),
                ('cover_letter', models.TextField(verbose_name='Why join us?')),
                ('status', models.CharField(default='new', max_length=30, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.company')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('description', models.TextField(blank=True, verbose_name='Job Description')),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base Salary ($)')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Per Hour ($)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='api.company')),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'ordering': ['title'],
                'unique_together': {('company', 'title')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager')], default='recruiter', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30, verbose_name='Stage')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='api.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='api.jobposition')),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
                'unique_together': {('position', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name='Key')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.company')),
            ],
            options={
                'verbose_name': 'Pipeline Stage',
                'verbose_name_plural': 'Pipeline Stages',
                'ordering': ['order'],
                'unique_together': {('company', 'key')},
            },
        ),
    ]
