# Generated by Django 5.2.15 on 2026-07-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('undecided', 'Undecided'), ('reviewing', 'Reviewing'), ('liked', 'Liked'), ('contacted', 'Contacted'), ('screening', 'Screening'), ('screening_passed', 'Screening Passed'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('offer_made', 'Offer Made'), ('background_check', 'Background Check'), ('verify_eligibility', 'Verify Eligibility'), ('hired', 'Hired'), ('onboarding', 'Onboarding')], default='new', max_length=30, verbose_name='Status'),
        ),
    ]
