# Generated by Django 6.0.2 on 2026-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
    ]
