# Generated by Django 5.2.15 on 2026-07-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base Salary ($)'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Per Hour ($)'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='description',
            field=models.TextField(blank=True, verbose_name='Job Description'),
        ),
    ]
