# Generated by Django 6.0.7 on 2026-07-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userauth_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, help_text='Street, city, state, zip', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief description of the company', verbose_name='Summary'),
        ),
    ]
