# Generated by Django 5.2.15 on 2026-07-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobposition_base_salary_jobposition_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('need_info', 'Need Info'), ('screening', 'Screening'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('selected', 'Selected'), ('background_check', 'Background Check'), ('offer_sent', 'Offer Sent'), ('accepted', 'Accepted'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected')], default='new', max_length=30, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'New'), ('need_info', 'Need Info'), ('screening', 'Screening'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('selected', 'Selected'), ('background_check', 'Background Check'), ('offer_sent', 'Offer Sent'), ('accepted', 'Accepted'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected')], max_length=30, verbose_name='Stage')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='api.jobposition')),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
                'unique_together': {('position', 'stage')},
            },
        ),
    ]
