# Generated by Django 6.0.7 on 2026-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_address_company_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address matching the website domain', max_length=254, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website (e.g. https://acme.com)', verbose_name='Website'),
        ),
    ]
