# Generated by Django 5.2.15 on 2026-07-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_application_status_automation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='Key')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Pipeline Stage',
                'verbose_name_plural': 'Pipeline Stages',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='new', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='stage',
            field=models.CharField(max_length=30, verbose_name='Stage'),
        ),
    ]
