# Generated by Django 5.2.16 on 2026-07-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_company_email_company_website'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'company')},
        ),
    ]
