# Generated by Django 6.0.7 on 2026-07-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userrole_unique_together'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='company.company'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='company.company'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='company.company'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='company.company'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company.company'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='company.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
