# Generated by Django 6.0.7 on 2026-07-22 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_skill_application_generated_cover_letter_and_more'),
        ('company', '0003_alter_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('specialization', models.TextField(blank=True, verbose_name='Specialization')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='company.company')),
            ],
            options={
                'verbose_name': 'Panelist',
                'verbose_name_plural': 'Panelists',
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_type', models.CharField(blank=True, max_length=200, verbose_name='Screening Type')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At')),
                ('duration_minutes', models.PositiveIntegerField(default=45, verbose_name='Duration (min)')),
                ('meeting_link', models.URLField(blank=True, max_length=500, verbose_name='Meeting Link')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score')),
                ('status', models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='api.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='company.company')),
                ('panelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='api.panelist')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='api.jobposition')),
            ],
            options={
                'verbose_name': 'Screening',
                'verbose_name_plural': 'Screenings',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
