# Generated by Django 6.0.7 on 2026-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_panelist_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='experience_required',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience Required (years)'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Salary ($)'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='work_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On-site')], default='on_site', max_length=20, verbose_name='Work Type'),
        ),
    ]
