# Generated by Django 6.0.7 on 2026-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jobposition_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/', verbose_name='Profile Photo'),
        ),
    ]
