# Generated by Django 6.0.7 on 2026-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('slug', models.SlugField(help_text='Used in URL: /slug/...', max_length=100, unique=True, verbose_name='Slug')),
                ('brand_color', models.CharField(default='#f59e0b', help_text='Hex color for branding', max_length=7, verbose_name='Brand Color')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, help_text='Company website (e.g. https://acme.com)', verbose_name='Website')),
                ('email', models.EmailField(blank=True, help_text='Email address matching the website domain', max_length=254, verbose_name='Company Email')),
                ('address', models.TextField(blank=True, help_text='Street, city, state, zip', verbose_name='Address')),
                ('summary', models.TextField(blank=True, help_text='Brief description of the company', verbose_name='Summary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'api_company',
            },
        ),
    ]
