# Generated by Django 6.0.7 on 2026-07-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Company Name')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Company Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('brand_color', models.CharField(blank=True, max_length=7, verbose_name='Brand Color')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_edit_logos/', verbose_name='Logo')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='company.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Edit Request',
                'verbose_name_plural': 'Company Edit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
