# Generated by Django 5.2.16 on 2026-07-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyeditrequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
    ]
